import React, {useState} from 'react';
import axios from 'axios';
import useSWR from 'swr';
import { getCookie } from 'cookies-next';
import { setCookie } from 'cookies-next';




function PaymentHistory () {
    
    
    const token =(getCookie('token'));
    const fetcher = (url) => axios.get(url,
        {
            headers:{
                Authorization:`Bearer ${token}`,
                'Content-Type' : 'application/json',
                'Accept': 'application/json'}
            } ).then(res=>res.data.pass_payments)
    const {data, error} = useSWR('https://metro-card.herokuapp.com/pass/all-payments',fetcher,
    {
       refreshInterval: 500,
        shouldRetryOnError: true,
        
        });

       
        
        //console.log(data);
      

        var payments = data;
        //This sort code was generated by Github Co-pilot
       //data.sort(function(a, b){return b.id-a.id});
       //console.log(payments);
       
       if(!payments){
       // console.log('loading');
        }else{
            data.sort(function(a, b){return b.id-a.id});
            
        }
      
        
    
return(

  <>
                       

                        { payments && payments.slice(0,5).map((payment,index) => (
                       
                        <div className="p-5 mb-3 ml-10 mr-10 border border-solid shadow-md rounded-xl border-slate-100 hover:bg-gray-100" key={payment.id}>
                            <div className="flex flex-row">
                                <div className="basis-3/4">
                                <p className='font-bold'>{payment.reg_no}</p>
                                <p className='text-sm font-light text-slate-400'>{payment.created_at}</p>

                                </div>
                                <div className="basis-1/4">
                                <p className='text-lg font-thin text-right text-slate-600'>Ksh {payment.amount}</p>
                                

                                </div>
                                
                            </div>
                          

                        </div>
                        ))}
                        

                   
 </>
)


      }

export default PaymentHistory;