import React, {useState} from 'react';
import axios from 'axios';
import useSWR from 'swr';
import { getCookie } from 'cookies-next';






function TopupHistory () {
    
    
    const token =(getCookie('token'));
    const fetcher = (url) => axios.get(url,
        {
            headers:{
                Authorization:`Bearer ${token}`,
                'Content-Type' : 'application/json',
                'Accept': 'application/json'}
            } ).then(res=>res.data.pass_topups)
    const {data, error} = useSWR('https://metro-card.onrender.com/pass/all-topup',fetcher,
    {
       refreshInterval: 500,
        shouldRetryOnError: true,
        
        });

       
        
        //console.log(data);
      

        var topups = data;
        //This sort code was generated by Github Co-pilot
       //data.sort(function(a, b){return b.id-a.id});
       //console.log(topups);
       //console.log(topups);
      try {
        if(!topups){
            //console.log('loading');
            
            }else{
                data.sort(function(a, b){return b.id-a.id});
            }
        
      } catch (error) {
        console.log(error);
      }
       
    
return(

  <>
 

                        { topups && topups.slice(0,5).map((topup,index) => (
                       
                        <div className="p-5 mb-3 ml-10 mr-10 border border-solid shadow-md rounded-xl border-slate-100 hover:bg-gray-100" key={topup.id}>
                            <div className="flex flex-row">
                                <div className="basis-3/4">
                                <p className='font-bold uppercase'>{topup.mpesa_code}</p>
                                <p className='text-sm font-light text-slate-400'>{topup.created_at}</p>

                                </div>
                                <div className="basis-1/4">
                                <p className='text-lg font-thin text-right text-slate-600'>Ksh {topup.amount}</p>
                                <p className='text-sm font-light text-right text-slate-400'>{topup.status}</p>
                                

                                </div>
                                
                            </div>
                          

                        </div>
                        ))}
                        

                   
 </>
)


      }

export default TopupHistory;
